build:
  environment:
    php: 7.4
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
    excluded_paths: [Test/*]

tools:
  external_code_coverage:
    runs: 8
